yolo_model:

  config_file:
    name: yolov3-tiny_xx.cfg
  weight_file:
    name: yolov3-tiny_xx_10000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - paomo
      - nongfu
      - milk_box
      - maidong
      - kuaiyin

